### ISSUE TITLE
Incorrect legend labelling using plotOneExp

### ISSUE THREAD

**Issue by pgreninger** [nickytong/drexplorer#3]
When fitting multiple models, if some of the models are NULL the IC50 and RSE values in the plot legend will be off.  I believe the problem stems from using `models` instead of `models[indSuccess]` in `str_c()`.  See lines 252, 256 and 260 in **aux_from_Extra.R**

**Comment by nickytong** [comment]
Thanks for pointing this out. The discrepancy has been fixed.
